version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.13.0-pg14
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sanlam
    ports:
      - "5433:5432"